services:
  vn-database:
    image: neo4j:5.18.0-community
    container_name: vn-database
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/plugins:/plugins
    environment:
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_import_file_use__neo4j__config: "true"
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_AUTH: ${NEO4J_AUTH}
    networks:
      - vn-shared-network

  vn-api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: vn-api
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      NEO4J_URI: bolt://vn-database:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: fi-hauQkWZ3Tn6N8qBaqqsR4f9S_uB-oFcgAr0Dkqi0
    depends_on:
      - vn-database
    volumes:
      # Sync all source code
      - ./src:/app/src
      - ./scripts:/app/scripts
      - ./tests:/app/tests
      - ./api.py:/app/api.py
      - ./main.py:/app/main.py
      - ./requirements.txt:/app/requirements.txt
      # Sync .env file
      - ./.env:/app/.env
      # Sync logs and outputs
      - ./outputs:/app/outputs
      - ./logs:/app/logs
    networks:
      - vn-shared-network

networks:
  vn-shared-network:
    external: true